#!/bin/bash
cd "$(dirname "$0")"
bash figure4/ace_run_steal_attack_craftME_vgg11bn_cifar10_diff_arch.sh
bash figure4/ace_run_steal_attack_GMME_vgg11bn_cifar10_diff_arch.sh
bash figure4/ace_run_steal_attack_ganME_vgg11bn_cifar10_diff_arch.sh
bash figure4/ace_run_steal_attack_softTrainME_vgg11bn_cifar10_diff_arch.sh
bash figure4/ace_run_steal_attack_TrainME_vgg11bn_cifar10_diff_arch.sh