#!/bin/bash
cd "$(dirname "$0")"

# bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_craft.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_craft_resume.sh
# bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_gan.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_gan_resume.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_GM.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_GM_resume.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_soft.sh
bash figure5_mobilenet/ace_run_mobilenet_cifar10_train_soft_resume.sh